.\" Manpage for palantir
.TH PALANTIR 1
.SH NAME
Palantir \- Lua Reverse Shell
.SH SYNOPSIS
palantir [-dhlv] [-a TOKEN] HOST PORT
.SH DESCRIPTION
Palantir is a Lua scriptable, portable, tiny reverse shell.
.SH OPTIONS
.IP "-d"
Start as server
.IP "-h"
Shows the usage information
.IP "-l"
Shows the license
.IP "-v"
Shows the version
.IP "-a"
Authentication token
.SH FILES
.I ~/.palantir.lua
.RS
Executed at start
.RE
.SH AUTHOR
Christian Uhsat <christian@uhsat.de>